# Generated by Django 5.0.6 on 2024-06-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dynamic Text',
                'verbose_name_plural': 'Dynamic Texts',
            },
        ),
        migrations.CreateModel(
            name='OG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='og')),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Open Graph',
                'verbose_name_plural': 'Open Graphs',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('keywords', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('dynamic_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_texts', to='app.dynamictexts')),
            ],
            options={
                'verbose_name': 'Footer Text',
                'verbose_name_plural': 'Footer Texts',
            },
        ),
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dynamic_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_texts', to='app.dynamictexts')),
            ],
            options={
                'verbose_name': 'Header Text',
                'verbose_name_plural': 'Header Texts',
            },
        ),
    ]
