# Generated by Django 5.0.6 on 2024-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Header Text',
                'verbose_name_plural': 'Header text',
            },
        ),
        migrations.CreateModel(
            name='OG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='og')),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Open Graph',
                'verbose_name_plural': 'Open Graphs',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('keywords', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'seo',
                'verbose_name_plural': 'seo',
            },
        ),
    ]
