# Generated by Django 5.0.6 on 2024-06-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OG',
        ),
        migrations.DeleteModel(
            name='SEO',
        ),
    ]
