# Generated by Django 5.0.6 on 2024-06-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_og_delete_seo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='dynamic_text',
        ),
        migrations.DeleteModel(
            name='HeaderText',
        ),
        migrations.DeleteModel(
            name='DynamicTexts',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
