# Generated by Django 5.0.6 on 2024-06-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_leftblock_rightblock_alter_treeblocks_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcessMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Work Process',
                'verbose_name_plural': 'Work Process',
            },
        ),
        migrations.CreateModel(
            name='WorkProcessChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='work-process')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.workprocessmain')),
            ],
        ),
    ]
