# Generated by Django 5.0.6 on 2024-07-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_pricingplanmain_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
