# Generated by Django 5.0.6 on 2024-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pricingplancategory_delete_pricingplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('space', models.CharField(max_length=255)),
                ('transfer', models.CharField(max_length=255)),
                ('panel', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=255)),
                ('emails', models.CharField(max_length=255)),
                ('security', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
            },
        ),
        migrations.DeleteModel(
            name='PricingPlanCategory',
        ),
    ]
