# Generated by Django 5.0.6 on 2024-07-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_pricingplan_delete_pricingplancategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_panel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_security',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_space',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_transfer',
            field=models.BooleanField(default=True),
        ),
    ]
