# Generated by Django 5.0.6 on 2024-07-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_pricingplan_is_emails_pricingplan_is_panel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headertext',
            options={'verbose_name': 'Header Text', 'verbose_name_plural': 'Header Texts'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='workprocess',
            options={'verbose_name': 'Work process', 'verbose_name_plural': 'Work process'},
        ),
    ]
