# Generated by Django 5.0.6 on 2024-07-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessage',
            new_name='Message',
        ),
    ]
